# Application constants
DEFAULT_SEVERITY_LEVELS = ['Low', 'Medium', 'High', 'Critical']
DEFAULT_MACHINE_STATUSES = ['Good', 'Warning', 'Alert', 'Offline']
DEFAULT_OUTCOME_RESOLVED = 'RESOLVED'
DEFAULT_OUTCOME_FAILED = 'FAILED'


MAX_PAGE_LIMIT = 500
DEFAULT_PAGE_LIMIT = 50


CACHE_TTL_HEALTH_SECONDS = 5
CACHE_TTL_METRICS_SECONDS = 15


MIN_DIAGNOSTIC_CONFIDENCE = 0.65
RECOMMENDED_CONFIDENCE_THRESHOLD = 0.85
